$init_ssh = <<-SCRIPT
# 允许root使用ssh登录
sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
# 允许使用密码登录
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo systemctl restart sshd
SCRIPT


$instead_yum_source = <<-SCRIPT
sudo yum install wget -y
cd /etc/yum.repos.d
sudo mv CentOS-Base.repo CentOS-Base.repo.bk
wget http://mirrors.163.com/.help/CentOS6-Base-163.repo
# 生成缓存
yum makecache
SCRIPT


$install_nginx = <<-'SCRIPT'
# https://nginx.org/en/linux_packages.html#RHEL-CentOS
sudo yum install yum-utils -y
echo "[nginx-stable]
name=nginx stable repo
baseurl=http://nginx.org/packages/centos/7Server/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://nginx.org/keys/nginx_signing.key
module_hotfixes=true

[nginx-mainline]
name=nginx mainline repo
baseurl=http://nginx.org/packages/mainline/centos/7Server/x86_64/
gpgcheck=1
enabled=0
gpgkey=https://nginx.org/keys/nginx_signing.key
module_hotfixes=true" > /etc/yum.repos.d/nginx.repo

yum list nginx
sudo yum install nginx -y
SCRIPT


$run_nginx = <<-SCRIPT
sudo nginx
ps -ax | grep nginx
SCRIPT


$install_keepalived = <<-SCRIPT
sudo yum install keepalived -y
SCRIPT

Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "nginx-cluster-#{i}" do |node|
            # 设置虚拟机的Box
            node.vm.box = "centos/7"

            # 设置虚拟机的主机名
            node.vm.hostname="centos7-nginx-#{i}"

            # 设置虚拟机的IP，根据VirtualBox Host-Only Network配置
            node.vm.network "private_network", ip: "192.168.56.#{110+i}", netmask: "255.255.255.0"

            # 设置主机与虚拟机的共享目录
            # node.vm.synced_folder "~/Documents/vagrant/share", "/home/vagrant/share"

            # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "centos7-nginx-#{i}"
                # 设置虚拟机的内存大小
                v.memory = 1024
                # 设置虚拟机的CPU个数
                v.cpus = 2
            end

        # https://www.vagrantup.com/docs/provisioning/basic_usage
        # 配置SSH登录
        config.vm.provision "init_ssh",
            type: "shell",
            preserve_order: true,
            inline: $init_ssh
        # 更新源
        config.vm.provision "instead_yum_source",
            type: "shell",
            preserve_order: true,
            inline: $instead_yum_source
        # 安装nginx
        config.vm.provision "install_nginx",
            type: "shell",
            preserve_order: true,
            inline: $install_nginx

        # 启动nginx
        config.vm.provision "run_nginx",
           type: "shell",
           preserve_order: true,
           inline: $run_nginx

        # 区分3台nginx
        config.vm.provision "tag_nginx",
           type: "shell",
           preserve_order: true,
           inline: "sudo sed -i 's/Welcome to nginx/Welcome to nginx 192.168.56.'$1'/' /usr/share/nginx/html/index.html",
           args: "#{110+i}"

        # 安装keepalived
        config.vm.provision "install_keepalived",
           type: "shell",
           preserve_order: true,
           inline: $install_keepalived
        end
	end
end